packages/sourcepoint_unified_cmp/lib/sourcepoint_unified_cmp.dart, packages/sourcepoint_unified_cmp_android/android/src/main/kotlin/de/thekorn/sourcepoint/unified/cmp/SourcepointUnifiedCmp.g.kt, packages/sourcepoint_unified_cmp_android/android/src/main/kotlin/de/thekorn/sourcepoint/unified/cmp/SourcepointUnifiedCmpPlugin.kt, packages/sourcepoint_unified_cmp_android/lib/sourcepoint_unified_cmp_android.dart, packages/sourcepoint_unified_cmp_android/lib/src/messages.g.dart, packages/sourcepoint_unified_cmp_android/pigeons/messages.dart, packages/sourcepoint_unified_cmp_platform_interface/lib/sourcepoint_unified_cmp_platform_interface.dart, packages/sourcepoint_unified_cmp_platform_interface/lib/src/types.dart
=> Fix android on action pubdata payload

packages/sourcepoint_unified_cmp/example/lib/main.dart, packages/sourcepoint_unified_cmp_android/android/src/main/kotlin/de/thekorn/sourcepoint/unified/cmp/SourcePointUnifiedCmpData.kt, packages/sourcepoint_unified_cmp_android/android/src/main/kotlin/de/thekorn/sourcepoint/unified/cmp/SourcepointUnifiedCmp.g.kt, packages/sourcepoint_unified_cmp_android/android/src/main/kotlin/de/thekorn/sourcepoint/unified/cmp/SourcepointUnifiedCmpPlugin.kt, packages/sourcepoint_unified_cmp_android/lib/sourcepoint_unified_cmp_android.dart, packages/sourcepoint_unified_cmp_android/lib/src/messages.g.dart, packages/sourcepoint_unified_cmp_android/pigeons/messages.dart, packages/sourcepoint_unified_cmp_platform_interface/lib/src/types.dart
=> Make load message configurable

CONTRIBUTING.md, README.md, packages/sourcepoint_unified_cmp/CONTRIBUTING.md, packages/sourcepoint_unified_cmp/README.md, release.sh
🔀 refactor: move contributing and requirements sections from README.md to CONTRIBUTING.md to separate project usage and contribution guidelines
🔧 fix(release.sh): add copying of CONTRIBUTING.md to release script to ensure it's included in releases
=> docs: create CONTRIBUTING.md to guide contributors

.editorconfig, CONTRIBUTING.md, cspell.json, melos.yaml, packages/sourcepoint_unified_cmp/example/android/app/src/main/kotlin/com/example/sourcepoint_unified_cmp/example/MainActivity.kt, packages/sourcepoint_unified_cmp_android/android/src/main/kotlin/de/thekorn/sourcepoint/unified/cmp/SourcePointUnifiedCmpData.kt, packages/sourcepoint_unified_cmp_android/android/src/main/kotlin/de/thekorn/sourcepoint/unified/cmp/SourcepointUnifiedCmpPlugin.kt
🔧 chore: add ktlint for Kotlin linting and formatting 📝 docs(CONTRIBUTING.md): add ktlint to the list of required packages 🔧 chore(melos.yaml): add ktlint command to the format script 🔧 chore(cspell.json): add ktlint to the dictionary 🎨 style: apply ktlint formatting to Kotlin files
🔥 remove unnecessary imports and comments in Kotlin files 👌 improve: reformat long function calls for better readability in Kotlin files
=> style: use ktlint to format kotlin code

packages/sourcepoint_unified_cmp_android/android/build.gradle
=> chore: upgrade sourcepoint cmplibrary from 7.6.1 to 7.7.0 for latest features and bug fixes

packages/sourcepoint_unified_cmp_ios/ios/sourcepoint_unified_cmp_ios.podspec
=> fix: pin ConsentViewController dependency to version 7.6.0 to ensure compatibility and prevent potential issues with future versions

CHANGELOG.md, packages/sourcepoint_unified_cmp/CHANGELOG.md, packages/sourcepoint_unified_cmp/analysis_options.yaml, packages/sourcepoint_unified_cmp/example/analysis_options.yaml, packages/sourcepoint_unified_cmp/pubspec.yaml, packages/sourcepoint_unified_cmp_android/CHANGELOG.md, packages/sourcepoint_unified_cmp_android/pubspec.yaml, packages/sourcepoint_unified_cmp_ios/CHANGELOG.md, packages/sourcepoint_unified_cmp_ios/pubspec.yaml, packages/sourcepoint_unified_cmp_platform_interface/CHANGELOG.md, packages/sourcepoint_unified_cmp_platform_interface/pubspec.yaml
=> Fix analyze

.github/dependabot.yaml
✨ feat(dependabot.yaml): add gradle package ecosystem for android package to improve dependency management
=> refactor: dependabot.yaml update directory paths for package ecosystems to reflect new project structure

.github/workflows/sonarcloud.yml
=> chore: Create sonarcloud.yml

packages/sourcepoint_unified_cmp/example/android/app/build.gradle, packages/sourcepoint_unified_cmp/example/android/build.gradle, packages/sourcepoint_unified_cmp/example/android/settings.gradle
🔧 refactor(settings.gradle): use pluginManagement for better plugin handling and version management
🔧 refactor(build.gradle): remove unnecessary dependencies and apply plugins via plugin DSL for better maintainability
🔧 refactor(settings.gradle): include flutter tools in build script for better integration with flutter sdk
=> refactor: build.gradle move plugins to top of the file for better readability and standardization

packages/sourcepoint_unified_cmp/example/lib/main.dart, packages/sourcepoint_unified_cmp_android/android/src/main/kotlin/de/thekorn/sourcepoint/unified/cmp/SourcepointUnifiedCmpPlugin.kt, packages/sourcepoint_unified_cmp_android/lib/sourcepoint_unified_cmp_android.dart
=> fix: 42 bug javalangruntimeexception methods marked with uithread must be executed on the main thread

packages/sourcepoint_unified_cmp/example/lib/main.dart
🔨 refactor(main.dart): wrap SourcepointUnifiedCMPBuilder with Scaffold for better structure and readability
🐛 fix(main.dart): handle error state in SourcepointUnifiedCMPBuilder to provide feedback to user when error occurs
=> style: example (main.dart): add MaterialApp properties for better UI experience

packages/sourcepoint_unified_cmp_ios/ios/sourcepoint_unified_cmp_ios.podspec
🔧 chore(sourcepoint_unified_cmp_ios.podspec): change homepage from placeholder to actual project URL for better project tracking
🔧 chore(sourcepoint_unified_cmp_ios.podspec): update author details from placeholder to actual author for better communication
=> docs: sourcepoint_unified_cmp_ios.podspec - update homepage and author details

.fvmrc, .github/workflows/sourcepoint_unified_cmp.yaml, .github/workflows/sourcepoint_unified_cmp_android.yaml, .github/workflows/sourcepoint_unified_cmp_ios.yaml, .github/workflows/sourcepoint_unified_cmp_platform_interface.yaml, .vscode/settings.json
=> chore: update Flutter version from 3.19.0 to 3.19.3 across all workflows and settings for consistency and to use the latest stable version

packages/sourcepoint_unified_cmp_ios/ios/sourcepoint_unified_cmp_ios.podspec
=> chore(ios): upgrade ios sourcepoint sdk to 7.6.5

CHANGELOG.md, packages/sourcepoint_unified_cmp/CHANGELOG.md, packages/sourcepoint_unified_cmp/pubspec.yaml, packages/sourcepoint_unified_cmp_android/CHANGELOG.md, packages/sourcepoint_unified_cmp_android/pubspec.yaml, packages/sourcepoint_unified_cmp_ios/CHANGELOG.md, packages/sourcepoint_unified_cmp_ios/pubspec.yaml, packages/sourcepoint_unified_cmp_platform_interface/CHANGELOG.md, packages/sourcepoint_unified_cmp_platform_interface/pubspec.yaml, release.sh
I messed up the release, trying to recover :(
- [ x] ❌ Breaking change (fix or feature that would cause existing functionality to change)
=> fix: Release 0.1.11

CONTRIBUTING.md, melos.yaml, packages/sourcepoint_unified_cmp/CONTRIBUTING.md
🔧 (CONTRIBUTING.md, melos.yaml, sourcepoint_unified_cmp/CONTRIBUTING.md): Remove flutter_plugin_tools from global activation and replace it with melos in format script for better package management and consistency
=> feat: remove discontinued dependency on flutter_plugin_tools

packages/sourcepoint_unified_cmp_ios/ios/sourcepoint_unified_cmp_ios.podspec
=> feat: Upgrade ConsentViewController dependency from 7.6.5 to 7.6.6 for better performance and bug fixes

packages/sourcepoint_unified_cmp/example/android/gradle/wrapper/gradle-wrapper.properties, packages/sourcepoint_unified_cmp/example/android/settings.gradle
=> feat: Upgrade Gradle wrapper from 8.2 to 8.6 for latest features and bug fixes

.github/workflows/sourcepoint_unified_cmp.yaml, .github/workflows/sourcepoint_unified_cmp_android.yaml, .github/workflows/sourcepoint_unified_cmp_ios.yaml, .github/workflows/sourcepoint_unified_cmp_platform_interface.yaml, .vscode/settings.json, packages/sourcepoint_unified_cmp/example/android/settings.gradle
…
⬆️  Upgrade Android application plugin version from 8.4.0 to 8.4.1 in settings.gradle for improved stability and features
=> feat: Update Flutter version from 3.22.0 to 3.22.1 in GitHub workflows and VSCode settings for better compatibility and performance

.github/workflows/sourcepoint_unified_cmp.yaml, .github/workflows/sourcepoint_unified_cmp_android.yaml, .github/workflows/sourcepoint_unified_cmp_ios.yaml, .github/workflows/sourcepoint_unified_cmp_platform_interface.yaml, CONTRIBUTING.md, setup_environment.sh
=> build: Update fvm

packages/sourcepoint_unified_cmp_android/android/src/main/kotlin/de/thekorn/sourcepoint/unified/cmp/SourcepointUnifiedCmpPlugin.kt
- Refactor `SourcepointUnifiedCmpPlugin` class in Android platform to improve code clarity and structure.
- Update event handler from deprecated "onMessageReady" to "onUIReady" following updated API specifications.
=> feat: Refactor Sourcepoint CMP plugin for clarity and update API

packages/sourcepoint_unified_cmp/example/android/gradle/wrapper/gradle-wrapper.properties, packages/sourcepoint_unified_cmp/example/android/settings.gradle, packages/sourcepoint_unified_cmp_android/android/build.gradle
- Upgrade Android plugin and Gradle versions to enhance compatibility and performance.
- Raise the compile SDK version to improve support for newer Android APIs.
- Ensure changes are synchronized across example project and main Android module to maintain consistency.
=> feat: Update Android build configurations

melos.yaml, packages/sourcepoint_unified_cmp_ios/ios/sourcepoint_unified_cmp_ios.podspec
=> chore: Update dependencies and reduce concurrency settings in melos

CONTRIBUTING.md, cspell.json, melos.yaml, setup_environment.sh
=> chore: use "coverde" to report test coverage after test:all is run

packages/sourcepoint_unified_cmp_flutter_inappwebview_extension/README.md
=> docs: fix docs for the inappwebview extension

melos.yaml, packages/sourcepoint_unified_cmp/test/sourcepoint_unified_cmp_test.mocks.dart, packages/sourcepoint_unified_cmp_platform_interface/lib/src/method_channel.dart, packages/sourcepoint_unified_cmp_platform_interface/test/sourcepoint_unified_cmp_platform_interface_test.mocks.dart
=> chore: sourcepoint_unified_cmp_platform_interface: add missing methods to the MethodChannel implementation (fixes #169)

.vscode/settings.json, packages/sourcepoint_unified_cmp_flutter_inappwebview_extension/test/sourcepoint_unified_cmp_flutter_inappwebview_extension_test.mocks.dart, packages/sourcepoint_unified_cmp_ios/ios/sourcepoint_unified_cmp_ios.podspec, setup_environment.sh
- Update development environment versions in `.vscode/settings.json` and `setup_environment.sh` for improved compatibility and tooling support.
- Upgrade dependency versions in iOS package to ensure compliance with the latest standards and stability enhancements.
=> chore: Update project dependencies and SDK paths

packages/sourcepoint_unified_cmp_ios/ios/sourcepoint_unified_cmp_ios.podspec
=> Update CMP on iOS

packages/sourcepoint_unified_cmp_android/android/src/main/kotlin/de/thekorn/sourcepoint/unified/cmp/SourcePointUnifiedCmpData.kt, packages/sourcepoint_unified_cmp_android/android/src/main/kotlin/de/thekorn/sourcepoint/unified/cmp/SourcepointUnifiedCmp.g.kt, packages/sourcepoint_unified_cmp_android/lib/sourcepoint_unified_cmp_android.dart, packages/sourcepoint_unified_cmp_android/lib/src/messages.g.dart, packages/sourcepoint_unified_cmp_android/pigeons/messages.dart, packages/sourcepoint_unified_cmp_ios/ios/Classes/SourcepointUnifiedCmpData.swift, packages/sourcepoint_unified_cmp_ios/ios/Classes/pigeons/SourcepointUnifiedCmp.g.swift, packages/sourcepoint_unified_cmp_ios/lib/sourcepoint_unified_cmp_ios.dart, packages/sourcepoint_unified_cmp_ios/lib/src/messages.g.dart, packages/sourcepoint_unified_cmp_ios/pigeons/messages.dart, packages/sourcepoint_unified_cmp_platform_interface/lib/src/types.dart
=> chore: merge Add dutch message language option
